
[build]
  # Forzamos el uso de npm scripts para que se utilicen los binarios locales de node_modules
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.22.0"

[[redirects]]
  # Soporte vital para Single Page Application (SPA) en Netlify
  from = "/*"
  to = "/index.html"
  status = 200
