[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.x"

[[redirects]]
  # Redirige todas las peticiones a index.html para que el enrutamiento del lado del cliente funcione
  from = "/*"
  to = "/index.html"
  status = 200