
[build]
  # Forzamos el comando de construcci√≥n para evitar el error 'remix command not found'
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.22.0"

[[redirects]]
  # Soporte para Single Page Application (SPA)
  from = "/*"
  to = "/index.html"
  status = 200
